### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by includebrasil** [codemaxbr/API-cPanel#1]
Codemaxbr, essa API está atualizada para trabalhar com o Cpanel a partir da v74?

Eu tô usando essa API sua desde 2016 mas no ano passado 03/2018 ela deixou de funcionar quando atualizei o servidor coma versão mais recente e descobri que ela entrou em desuso por conta de algumas modificações.

**Comment by codemaxbr** [comment]
@includebrasil Se não foi desabilitada o uso de "Chaves de acesso (cluster)", você pode continuar usando essa API. Se for o caso das novas versões do cPanel não permitirem mais as chaves. Vou fazer uma modificação para o uso dos Tokens de API.

**Comment by codemaxbr** [comment]
> Codemaxbr, essa API está atualizada para trabalhar com o Cpanel a partir da v74?
> 
> Eu tô usando essa API sua desde 2016 mas no ano passado 03/2018 ela deixou de funcionar quando atualizei o servidor coma versão mais recente e descobri que ela entrou em desuso por conta de algumas modificações.

@includebrasil Se não foi desabilitada o uso de "Chaves de acesso (cluster)", você pode continuar usando essa API. Se for o caso das novas versões do cPanel não permitirem mais as chaves. Vou fazer uma modificação para o uso dos Tokens de API.

**Comment by codemaxbr** [comment]
@includebrasil Se não foi desabilitada o uso de "Chaves de acesso (cluster)", você pode continuar usando essa API. Se for o caso das novas versões do cPanel não permitirem mais as chaves. Vou fazer uma modificação para o uso dos Tokens de API.
